name: "Docker init"
description: "Initializes Docker environment"

inputs:
  registry_root:
    description: "Domain of the container registry (i.e. docker.io)"
    required: true
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to AWS ECR
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry_root }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}